export const AuthStatus = {
  ANONYMOUS: "ANONYMOUS",
  AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",
  LOGGED_IN: "LOGGED_IN"
};

export const AuthActionType = {
  ATTEMPT_LOGIN: "AUTH/ATTEMPT_LOGIN",
  ATTEMPT_LOGOUT: "AUTH/ATTEMPT_LOGOUT",
  LOGIN_SUCCESS: "AUTH/LOGIN_SUCCESS",
  LOGIN_FAIL: "AUTH/LOGIN_FAILED",
  LOGOUT_SUCCESS: "AUTH/LOGOUT_SUCCESS",
  LOGOUT_FAIL: "AUTH/LOGOUT_FAILED"
};
